// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArrG4Ue2gwm0FBfbEkkusPOGmuF-T0f2Q',
    appId: '1:332026803647:web:9b3ccdaaea671007c2dd0a',
    messagingSenderId: '332026803647',
    projectId: 'spotifyproject-38cfe',
    authDomain: 'spotifyproject-38cfe.firebaseapp.com',
    storageBucket: 'spotifyproject-38cfe.firebasestorage.app',
    measurementId: 'G-J1WTE6Y9H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0LYAAUKY_0yurmi6wO9S9wZUCCVrgII',
    appId: '1:332026803647:android:385cf529cd950799c2dd0a',
    messagingSenderId: '332026803647',
    projectId: 'spotifyproject-38cfe',
    storageBucket: 'spotifyproject-38cfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCUr2ExphnumJJDBcW-JSQBZNVB7Bj8P8',
    appId: '1:332026803647:ios:d144852f816d932dc2dd0a',
    messagingSenderId: '332026803647',
    projectId: 'spotifyproject-38cfe',
    storageBucket: 'spotifyproject-38cfe.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCUr2ExphnumJJDBcW-JSQBZNVB7Bj8P8',
    appId: '1:332026803647:ios:d144852f816d932dc2dd0a',
    messagingSenderId: '332026803647',
    projectId: 'spotifyproject-38cfe',
    storageBucket: 'spotifyproject-38cfe.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArrG4Ue2gwm0FBfbEkkusPOGmuF-T0f2Q',
    appId: '1:332026803647:web:ca07d3eb12abcbdcc2dd0a',
    messagingSenderId: '332026803647',
    projectId: 'spotifyproject-38cfe',
    authDomain: 'spotifyproject-38cfe.firebaseapp.com',
    storageBucket: 'spotifyproject-38cfe.firebasestorage.app',
    measurementId: 'G-G4R8DB49LJ',
  );

}